version: '3.8'

services:
  # Python Streamlit web app
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    networks:
      - ei-network

  # JavaScript client
  js-client:
    build:
      context: ./js-client
      dockerfile: Dockerfile
    volumes:
      - ./js-client/.env:/app/.env
    depends_on:
      - streamlit-app
    networks:
      - ei-network

networks:
  ei-network:
    driver: bridge
